// Assemble styles.css, the one stylesheet Moodle will load for this plugin.
//
// Moodle includes <plugin>/styles.css and nothing else. The forked CSS lives in
// styles/ as four files, untouched, so that a diff against upstream stays
// readable — and until this script existed none of it reached a page at all.
// The player drew itself with no stylesheet: interactions landed below the
// video instead of on it, the controls were unstyled boxes, and the text meant
// only for screen readers was printed on the screen.
//
// Two rewrites are needed on the way through, both about paths.
//
//   url('../fonts/X') becomes [[font:mod_kaiiv|X]]
//   url('../gui/X.svg') becomes [[pix:mod_kaiiv|X]]
//
// Relative URLs cannot work here: Moodle serves this file from
// theme/styles.php, so '../fonts' resolves against the theme, not against the
// plugin. The placeholders are Moodle's own mechanism for exactly this, and it
// replaces them when it builds the theme's CSS.
//
// One font is supplied from Moodle rather than from the fork. Upstream uses
// 'H5PFontAwesome4', which H5P core loads and which we do not carry; Moodle
// already ships Font Awesome 6, and the only glyph the forked CSS asks for
// from it (\f058, a ticked circle) has the same code point there.
//
// Runs as part of npm run build. The output is committed, like amd/build,
// because a customer installing this plugin has a PHP host and no node.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

// Upstream's, in the order its own entry point imported them. Order matters
// for ties between their rules, so it is theirs, not alphabetical.
const FORKED = [
    'styles/interactive-video.css',
    'styles/accessibility.css',
    'styles/bubble.css',
    'styles/endscreen.css',
];

// Ours, last, so it wins a tie with anything above.
const OURS = 'styles/kaiiv.css';

const HEADER = `/*
 * GENERATED by tools/build-styles.js — edit styles/*.css, not this file.
 *
 * Most of what follows is forked from h5p-interactive-video (MIT, © 2017
 * H5P). See thirdparty/README.md and thirdparty/LICENCE-h5p-interactive-video.md.
 */

/* Upstream's H5PFontAwesome4, which H5P core would load, served from the Font
 * Awesome 6 that Moodle already ships. */
@font-face {
    font-family: 'H5PFontAwesome4';
    src: url([[font:core|fa-solid-900.woff2]]) format('woff2'),
         url([[font:core|fa-solid-900.ttf]]) format('truetype');
    font-weight: normal;
    font-style: normal;
}
`;

const rewrite = (css, file) => {
    let fonts = 0;
    let images = 0;

    const out = css
        // url('../fonts/h5p.woff?g5utfi') and url('../fonts/X.svg?v#name'):
        // the query string and the fragment are cache-busters and an SVG
        // font id respectively, and neither survives Moodle's font handler.
        .replace(/url\(\s*['"]?\.\.\/fonts\/([^'")?#]+)[^'")]*['"]?\s*\)/g,
            (match, name) => {
                fonts++;
                return `url([[font:mod_kaiiv|${name}]])`;
            })
        // url('../gui/score_h5p_green.svg'): pix placeholders take the name
        // without its extension, and Moodle finds the file in pix/.
        .replace(/url\(\s*['"]?\.\.\/gui\/([^'")]+?)\.(svg|png)['"]?\s*\)/g,
            (match, name) => {
                images++;
                return `url([[pix:mod_kaiiv|${name}]])`;
            });

    // Anything relative left over would resolve against the theme and 404
    // silently. Refused here instead, where the file and the url are named.
    const leftover = out.match(/url\(\s*['"]?\.\.?\//g);
    if (leftover) {
        throw new Error(file + ' still has ' + leftover.length
            + ' relative url() after rewriting; add a rule for it above');
    }

    return {out, fonts, images};
};

let css = HEADER;
let totalFonts = 0;
let totalImages = 0;

for (const file of FORKED) {
    const source = fs.readFileSync(path.join(ROOT, file), 'utf8');
    const {out, fonts, images} = rewrite(source, file);
    totalFonts += fonts;
    totalImages += images;
    css += `\n/* ---- ${file} (forked) ---- */\n` + out + '\n';
}

css += `\n/* ---- ${OURS} ---- */\n`
    + fs.readFileSync(path.join(ROOT, OURS), 'utf8');

// Every font and image the rewritten CSS now points at has to exist, or it
// fails the same quiet way a wrong relative path did.
const missing = [];
for (const [, name] of css.matchAll(/\[\[font:mod_kaiiv\|([^\]]+)\]\]/g)) {
    if (!fs.existsSync(path.join(ROOT, 'fonts', name))) {
        missing.push('fonts/' + name);
    }
}
for (const [, name] of css.matchAll(/\[\[pix:mod_kaiiv\|([^\]]+)\]\]/g)) {
    if (!['svg', 'png'].some((ext) => fs.existsSync(path.join(ROOT, 'pix', name + '.' + ext)))) {
        missing.push('pix/' + name);
    }
}
if (missing.length) {
    process.stderr.write('styles.css refers to files that are not here:\n  '
        + [...new Set(missing)].join('\n  ') + '\n');
    process.exit(1);
}

fs.writeFileSync(path.join(ROOT, 'styles.css'), css);
process.stdout.write(`wrote styles.css (${totalFonts} font url(s), `
    + `${totalImages} image url(s) rewritten)\n`);
