// Assemble the player's stylesheet, for either of the two places it goes.
//
//     node tools/build-styles.js                  dist/kaiiv-player.css
//     node tools/build-styles.js --moodle <dir>   <dir>/styles.css, for mod_kaiiv
//
// The forked CSS lives in styles/ as four files, untouched, so that a diff
// against upstream stays readable. What differs between the two outputs is
// only how its url()s are written, and one extra file:
//
//   standalone   url('../fonts/X') becomes url('fonts/X')
//                url('../gui/X.svg') becomes url('images/X.svg')
//                styles/standalone.css is appended (Bootstrap's part, the
//                icon font), and fonts/ and images/ are copied into dist/.
//
//   moodle       url('../fonts/X') becomes [[font:mod_kaiiv|X]]
//                url('../gui/X.svg') becomes [[pix:mod_kaiiv|X]]
//                Relative URLs cannot work there: Moodle serves the file from
//                theme/styles.php, so '../fonts' resolves against the theme.
//                The placeholders are Moodle's own mechanism for exactly this.
//                The files are copied into the plugin's fonts/ and pix/, where
//                Moodle looks for them. standalone.css is left out: the theme
//                already styles Bootstrap's classes, and Moodle ships the icon
//                font.
//
// Every file a rewritten url() points at has to exist, or it fails the same
// quiet way a wrong relative path did; the build refuses instead.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

// Upstream's, in the order its own entry point imported them. Order matters
// for ties between their rules, so it is theirs, not alphabetical.
const FORKED = [
    'styles/interactive-video.css',
    'styles/accessibility.css',
    'styles/bubble.css',
    'styles/endscreen.css',
];

// Ours, last, so it wins a tie with anything above.
const OURS = 'styles/kaiiv.css';
const STANDALONE = 'styles/standalone.css';

const FORK_FONTS = fs.readdirSync(path.join(ROOT, 'fonts'))
    .filter((name) => !name.startsWith('fa-'));
const IMAGES = fs.readdirSync(path.join(ROOT, 'images'));

const args = process.argv.slice(2);
const moodleAt = args.indexOf('--moodle');
const MOODLE = moodleAt !== -1 ? path.resolve(args[moodleAt + 1] || '') : null;

const HEADER_COMMON = ` * Most of what follows is forked from h5p-interactive-video (MIT, © 2017
 * H5P). See thirdparty/README.md and thirdparty/LICENCE-h5p-interactive-video.md.
 */
`;

const HEADER_MOODLE = `/*
 * GENERATED by kaiiv-player/tools/build-styles.js — edit the player's
 * styles/*.css, not this file.
 *
${HEADER_COMMON}
/* Upstream's H5PFontAwesome4, which H5P core would load, served from the Font
 * Awesome 6 that Moodle already ships. */
@font-face {
    font-family: 'H5PFontAwesome4';
    src: url([[font:core|fa-solid-900.woff2]]) format('woff2'),
         url([[font:core|fa-solid-900.ttf]]) format('truetype');
    font-weight: normal;
    font-style: normal;
}
`;

const HEADER_STANDALONE = `/*
 * KAISER interactive video player. GENERATED by tools/build-styles.js — edit
 * styles/*.css, not this file.
 *
${HEADER_COMMON}`;

const rewrite = (css, file) => {
    let fonts = 0;
    let images = 0;

    const out = css
        // url('../fonts/h5p.woff?g5utfi') and url('../fonts/X.svg?v#name'):
        // the query string and the fragment are cache-busters and an SVG
        // font id respectively, and neither survives Moodle's font handler.
        .replace(/url\(\s*['"]?\.\.\/fonts\/([^'")?#]+)[^'")]*['"]?\s*\)/g,
            (match, name) => {
                fonts++;
                return MOODLE ? `url([[font:mod_kaiiv|${name}]])` : `url("fonts/${name}")`;
            })
        // url('../gui/score_h5p_green.svg'): pix placeholders take the name
        // without its extension, and Moodle finds the file in pix/.
        .replace(/url\(\s*['"]?\.\.\/gui\/([^'")]+?)\.(svg|png)['"]?\s*\)/g,
            (match, name, ext) => {
                images++;
                return MOODLE ? `url([[pix:mod_kaiiv|${name}]])` : `url("images/${name}.${ext}")`;
            });

    // Anything relative to the source tree left over would resolve against
    // the wrong place and 404 silently. Refused here, where it is named.
    const leftover = out.match(/url\(\s*['"]?\.\.\//g);
    if (leftover) {
        throw new Error(file + ' still has ' + leftover.length
            + ' relative url() after rewriting; add a rule for it above');
    }

    return {out, fonts, images};
};

const copy = (from, to) => {
    fs.mkdirSync(path.dirname(to), {recursive: true});
    fs.copyFileSync(from, to);
};

let css = MOODLE ? HEADER_MOODLE : HEADER_STANDALONE;
let totalFonts = 0;
let totalImages = 0;

for (const file of FORKED) {
    const source = fs.readFileSync(path.join(ROOT, file), 'utf8');
    const {out, fonts, images} = rewrite(source, file);
    totalFonts += fonts;
    totalImages += images;
    css += `\n/* ---- ${file} (forked) ---- */\n` + out + '\n';
}

css += `\n/* ---- ${OURS} ---- */\n` + fs.readFileSync(path.join(ROOT, OURS), 'utf8');

if (!MOODLE) {
    css += `\n/* ---- ${STANDALONE} ---- */\n` + fs.readFileSync(path.join(ROOT, STANDALONE), 'utf8');
}

// Where the files go, and a check that every url() has one.
const fontsDir = MOODLE ? path.join(MOODLE, 'fonts') : path.join(ROOT, 'dist/fonts');
const imagesDir = MOODLE ? path.join(MOODLE, 'pix') : path.join(ROOT, 'dist/images');

const fontNames = MOODLE ? FORK_FONTS : fs.readdirSync(path.join(ROOT, 'fonts'));
fontNames.forEach((name) => copy(path.join(ROOT, 'fonts', name), path.join(fontsDir, name)));
IMAGES.forEach((name) => copy(path.join(ROOT, 'images', name), path.join(imagesDir, name)));

const missing = [];
const fontRef = MOODLE ? /\[\[font:mod_kaiiv\|([^\]]+)\]\]/g : /url\("fonts\/([^"]+)"\)/g;
const imageRef = MOODLE ? /\[\[pix:mod_kaiiv\|([^\]]+)\]\]/g : /url\("images\/([^"]+)"\)/g;
for (const [, name] of css.matchAll(fontRef)) {
    if (!fs.existsSync(path.join(fontsDir, name))) {
        missing.push('fonts/' + name);
    }
}
for (const [, name] of css.matchAll(imageRef)) {
    const candidates = MOODLE ? ['svg', 'png'].map((ext) => name + '.' + ext) : [name];
    if (!candidates.some((file) => fs.existsSync(path.join(imagesDir, file)))) {
        missing.push('images/' + name);
    }
}
if (missing.length) {
    process.stderr.write('the stylesheet refers to files that are not there:\n  '
        + [...new Set(missing)].join('\n  ') + '\n');
    process.exit(1);
}

const target = MOODLE ? path.join(MOODLE, 'styles.css') : path.join(ROOT, 'dist/kaiiv-player.css');
fs.mkdirSync(path.dirname(target), {recursive: true});
fs.writeFileSync(target, css);
process.stdout.write(`wrote ${path.relative(process.cwd(), target)} (${totalFonts} font url(s), `
    + `${totalImages} image url(s) rewritten)\n`);
